name = "fastprize"
type = "javascript"
routes = [
  '*fastprize.org/checkout',
  '*fastprize.org/share/*',
  '*fastprize.org/stats*',
  '*fastprize.org/badge/*'
]
account_id = 'd3934b9b324240bf989664e018097273'
zone_id = '0e53dedb5a5794ef894d3d652149caab'
usage_model = 'unbound'
compatibility_flags = []
workers_dev = false
compatibility_date = "2021-10-06"

[build]
command = "yarn && yarn build-worker"

[build.upload]
format = "service-worker"
