name = "atomsprize"
type = "javascript"
account_id = 'd3934b9b324240bf989664e018097273'
usage_model = 'unbound'
compatibility_flags = []
workers_dev = true
compatibility_date = "2021-10-06"

[build]
command = "yarn && yarn build"

[build.upload]
format = "service-worker"
